rewrite trento community checks regarding 'sbd' configuration
trento-project/wanda pull request #123
Opened 2022-12-08 11:50 UTC by angelabriel

fixing jsc#CFSA-1062, jsc#CFSA-1083, jsc#CFSA-1098, jsc#CFSA-1092

2022-12-12 09:49 UTC, nelsonkopliku requested changes
Very nice! Thanks!

I followed discussion https://github.com/trento-project/wanda/discussions/121
and left some comments about removing redundancy of some values conditions.

I also noticed an inconsistency in the values expectations for check `49591F` with the current implementation.

2022-12-12 12:06 UTC, angelabriel commented on priv/catalog/0B6DB2.yaml
> +    conditions:
true. Fix is on it's way.

2022-12-12 12:11 UTC, angelabriel commented on priv/catalog/49591F.yaml
> +    conditions:
It's the same as for the other sbd checks. It should only run on 'azure', 'kvm' and 'nutanix' and there the values needs to be 'always'. So a 'clean' will never be a valid value. The 'notUsed' is a leftover of my attempts to workaround the situation discussed in https://github.com/trento-project/wanda/discussions/121. I will fix it as all the other sbd checks.

2022-12-12 12:12 UTC, angelabriel commented on priv/catalog/816815.yaml
> +    conditions:
fixed

2022-12-12 15:10 UTC, nelsonkopliku approved these changes

2022-12-22 09:17 UTC, arbulu89 reviewed
Super nice job!
I just did some nitpick comments about conventions of using `quotes` and small/capital letters.
Maybe we should discuss all of us to find the proper convention and write them down somewhere

2022-12-22 09:17 UTC, arbulu89 commented on priv/catalog/0B6DB2.yaml
> +  - name: sbd_SBD_PACEMAKER
I would stick to small case `sbd_pacemaker`. Mixing looks strange, even though I know that you did it to use the "real" value

2022-12-22 09:17 UTC, arbulu89 commented on priv/catalog/49591F.yaml
> +    default: "clean"
Let's remove quotes from here and next values. I see some checks with them and other without.
This is clear string, so it shouldn't be needed

2022-12-22 09:17 UTC, arbulu89 commented on priv/catalog/49591F.yaml
> +  - name: sbd_SBD_STARTMODE
The same for the small/capital letter convention

2022-12-22 09:17 UTC, arbulu89 commented on priv/catalog/61451E.yaml
> +    expect: facts.sbd_multiple_SBD_DEVICE.split(";").len() == values.expected_multiple_SBD_DEVICE
Nice!

2023-01-11 08:06 UTC, merged