Add doc for the new package_version comparisons
trento-project/wanda pull request #162
Opened 2023-01-16 11:32 UTC by rtorrero

This PR documents the changes introduced in PR https://github.com/trento-project/agent/pull/169

2023-01-16 11:41 UTC, fabriziosestito requested changes
@rtorrero let's wait to merge #160 and base this PR on the new format

2023-01-16 14:43 UTC, nelsonkopliku reviewed
Good job!

When it comes to the spec, we might want to consider suggesting putting some emphasis in facts and expectation names to clarify further. 

```yaml
expect: facts.package_corosync = 1 # or  facts.package_corosync > 0
expect: facts.package_corosync = 0
expect: facts.package_corosync = -1 # or facts.package_corosync < 0
```
At a first glance `facts.package_corosync = 1` might not sound immediately telling _Installed Corosync version must be equal or higher than the recommended value_ (DC5429)

2023-01-17 07:55 UTC, fabriziosestito approved these changes
Just one comment then LGTM :shipit:

2023-01-17 07:55 UTC, fabriziosestito commented on guides/gatherers.md
> + - A value of `1` if the provided version string is newer than what's currently installed.
we can mention the rpmvercmp algorithm somewhere here (with a link to the algorithm i.e. https://fedoraproject.org/wiki/Archive:Tools/RPM/VersionComparison#The_rpmvercmp_algorithm) as the user might be familiar with it

2023-01-17 08:09 UTC, nelsonkopliku approved these changes

2023-01-17 10:03 UTC, merged