Add premium flag option to catalog loading code
trento-project/wanda pull request #163
Opened 2023-01-16 13:27 UTC by arbulu89

2023-01-16 15:16 UTC, nelsonkopliku approved these changes
Premium :tm:

2023-01-16 15:16 UTC, EMaksy reviewed
LGTM :D

2023-01-16 16:20 UTC, dottorblaster requested changes
Just a tiny change request then I think we can merge

2023-01-16 16:20 UTC, dottorblaster commented on test/support/factory.ex
> +      premium: false
```suggestion
      premium: Enum.random([true, false])
```

2023-01-17 07:30 UTC, arbulu89 commented on test/support/factory.ex
> +      premium: false
Done

2023-01-17 07:51 UTC, fabriziosestito approved these changes

2023-01-17 07:52 UTC, merged