Disp work gatherer docs
trento-project/wanda pull request #323
Opened 2023-10-19 13:59 UTC by arbulu89

Docs for the `disp+work` gatherer:
https://github.com/trento-project/agent/pull/281

2023-10-23 08:10 UTC, EMaksy commented on guides/gatherers.md
> +| [`saphostctrl`](#saphostctrl)           | [trento-project/agent/../gatherers/saphostctrl.go](https://github.com/trento-project/agent/blob/main/inAternal/factsengine/gatherers/saphostctrl.go)
Typo in the link
`inAternal`should be `internal` right?

2023-10-23 08:13 UTC, EMaksy requested changes
Hey man besides the typo/broken link nothing to add, well done :D

2023-10-23 11:15 UTC, EMaksy approved these changes
LGTM :D

2023-10-24 10:10 UTC, rtorrero approved these changes
LGTM

2023-10-24 12:05 UTC, merged