Add premium deprecation warning
trento-project/wanda pull request #522
Opened 2024-10-11 07:58 UTC by janvhs

This commit partly reverts 51765fb, but adds a deprecation annotation. This enables check authors to spot the deprecation using other tooling than tlint.  Furthermore, it allows us to add and remove deprecations without having to touch tlint every time.  Yes, this is part of the specification :D

Also https://github.com/trento-project/tlint/pull/24 needs it :P

2024-10-11 08:12 UTC, EMaksy approved these changes
LGTM :)

2024-10-11 08:15 UTC, gagandeepb reviewed
Are you sure that draft7 dialect supports the deprecated annotation? I thought it was the draft2019 dialect.

2024-10-11 08:24 UTC, gagandeepb requested changes
Can you please link here the relevant bit from the draft7 doc that specifies support for the `deprecation` key word?

2024-10-11 08:47 UTC, gagandeepb reviewed
Would you like to add some [CLI/ CI based tests](https://github.com/python-jsonschema/check-jsonschema) somewhere to verify the intended behaviour ?

2024-10-14 06:59 UTC, dottorblaster commented
@gagandeepb thanks for your feedback!

I see two key parts in it:

- Linking to the right spec :heavy_check_mark: 
- Having a set of linting tools for the openAPI spec: I would like to discuss this for the future and defer at the moment.

2024-10-14 06:59 UTC, dottorblaster approved these changes

2024-10-14 07:33 UTC, gagandeepb approved these changes

2024-10-14 07:33 UTC, merged