Add Result OpenAPI Schema and cleanup
trento-project/wanda pull request #53
Opened 2022-10-12 13:03 UTC by fabriziosestito

Add Result OpenAPI Schema, general clean-up

NOTE: I've changed the already existing migration because the `timestamps` types were not populated correctly. Since we do not want to bloat the migration folders while in this early stages, please reset your ecto db with `mix ecto.reset` and `MIX_ENV=test mix ecto.reset`

2022-10-12 14:00 UTC, nelsonkopliku approved these changes
LGTM

2022-10-12 17:26 UTC, dottorblaster approved these changes
Mega LGTM, sorry you had to go through this

2022-10-13 07:03 UTC, arbulu89 requested changes
Hey @fabriziosestito ,
Some few changes needed in the schemas (copy/paste leftovers XD)

2022-10-13 07:04 UTC, fabriziosestito commented on lib/wanda/execution/agent_check_result.ex
> +    values: [],
yes it is a default value

2022-10-13 07:06 UTC, fabriziosestito commented on lib/wanda_web/controllers/result_controller.ex
> +        type: %Schema{
yes because this is an `OperationParameter` or similar, so you need to do this apparently

2022-10-13 07:32 UTC, dottorblaster approved these changes
LGTM

2022-10-13 07:42 UTC, fabriziosestito commented on lib/wanda_web/schemas/result/agent_check_error.ex
> +        description: "Agent ID"
i think we can remove this since the `ExpectationEvaluation` has already a description

2022-10-13 08:19 UTC, arbulu89 commented on test/support/factory.ex
> +              agent_id: UUID.uuid4(),
Nice!

2022-10-13 08:19 UTC, arbulu89 approved these changes

2022-10-13 08:24 UTC, merged